name: PR Description Check

on:
  pull_request:
    types: [opened, synchronize]  # Trigger on PR creation and when new commits are added

jobs:
  validate-pr-description:
    runs-on: ubuntu-latest
    steps:
      - name: Validate PR Description
        id: check_description
        run: |
          description="${{ github.event.pull_request.body }}"
          if [ -z "$description" ]; then
            echo "::error::PR description is missing!"
            exit 1
          else
            echo "PR Description is present."
          fi

      - name: Check for issue number or 'Fixes #NEW'
        id: check_issue_number
        run: |
          description="${{ github.event.pull_request.body }}"
          if [[ ! "$description" =~ (Fixes #[0-9]+|Fixes #NEW) ]]; then
            echo "::error::PR description must contain an issue number or 'Fixes #NEW'"
            exit 1
          else
            echo "PR description contains an issue number or 'Fixes #NEW'."
          fi
